function apply_axes_style(ax, style, size_class)
%APPLY_AXES_STYLE Apply shared type, grid, line, and interpreter roles to axes.
% ax is an axes handle or array; style is out.style; size_class is 'default'
% or 'small_multiple' (default), selecting font sizes from style.font_size
% fields by class. Updates ax, its Title, XLabel, YLabel, ZLabel in place.
    if nargin < 3 || isempty(size_class)
        size_class = 'default';
    end
    valid_size_classes = {'default', 'small_multiple'};
    if ~any(strcmp(size_class, valid_size_classes))
        error('mwecmass:figures:UnknownSizeClass', ...
              'size_class must be default or small_multiple.');
    end
    if strcmp(size_class, 'small_multiple')
        tick_size  = style.font_size.small_multiple;
        title_size = style.font_size.small_multiple;
        axes_size  = style.font_size.small_multiple;
    else
        tick_size  = style.font_size.tick_label;
        title_size = style.font_size.title;
        axes_size  = style.font_size.axes;
    end
    for k = 1:numel(ax)
        one = ax(k);
        set(one, 'FontName', style.font_name, ...
                 'FontSize', tick_size, ...
                 'LineWidth', style.line_width.axes, ...
                 'XGrid', 'on', 'YGrid', 'on', ...
                 'GridAlpha', style.grid.alpha, ...
                 'GridLineStyle', style.grid.line_style, ...
                 'TickLabelInterpreter', style.tick_label_interpreter);
        set(one.Title, 'FontName', style.font_name, ...
                       'FontSize', title_size, ...
                       'Interpreter', style.tick_label_interpreter);
        set(one.XLabel, 'FontName', style.font_name, ...
                        'FontSize', axes_size, ...
                        'Interpreter', style.tick_label_interpreter);
        set(one.YLabel, 'FontName', style.font_name, ...
                        'FontSize', axes_size, ...
                        'Interpreter', style.tick_label_interpreter);
        set(one.ZLabel, 'FontName', style.font_name, ...
                        'FontSize', axes_size, ...
                        'Interpreter', style.tick_label_interpreter);
    end
end
