function out = empty_realised_properties()
%EMPTY_REALISED_PROPERTIES Return a NaN-filled realised-property schema.
% feasible is false so callers can unpack a uniform struct for infeasible candidates.
    out = struct( ...
        'feasible',               false, ...
        'draft',                  NaN, ...
        'vertical_shift',         NaN, ...
        'V_steel',                NaN, ...
        'V_air',                  NaN, ...
        'V_shell',                NaN, ...  % two-density extension: solid region above z_fill
        'V_fill',                 NaN, ...  % two-density extension: solid region below z_fill
        'M_steel',                NaN, ...
        'M_air',                  NaN, ...
        'M_shell',                NaN, ...  % two-density extension
        'M_fill',                 NaN, ...  % two-density extension
        'M_total',                NaN, ...
        'mass_buoyant_force',     NaN, ...
        'mass_balance_error_abs', NaN, ...
        'z_cg_steel',             NaN, ...
        'z_cg_air',               NaN, ...
        'z_cg_shell',             NaN, ...  % two-density extension
        'z_cg_fill',              NaN, ...  % two-density extension
        'CG_z_body',              NaN, ...
        'CG_z_world',             NaN, ...
        'Iyy_total_origin',       NaN, ...
        'Iyy_about_cg',           NaN, ...
        'Ixx_total_origin',       NaN, ...
        'Ixx_about_cg',           NaN, ...
        'Izz_total_origin',       NaN, ...
        'Izz_about_cg',           NaN, ...
        'V_sub',                  NaN, ...
        'Aw',                     NaN, ...
        'I_wp_yy',                NaN, ...
        'CB_z_world',             NaN, ...
        'KM_world',               NaN, ...
        'GM',                     NaN, ...
        'T_heave',                NaN, ...
        'T_pitch',                NaN, ...
        'K33_hydro',              NaN, ...
        'K55_hydro',              NaN, ...
        'A11',                    NaN, ...
        'A33',                    NaN, ...
        'A55',                    NaN);
end
