function b = stp_new()
%STP_NEW  Empty B-rep struct for the STEP writer tests.

b = struct('vertices', zeros(0, 3), ...
    'curves', struct('degree', {}, 'ctrl', {}, 'knots', {}, 'weights', {}), ...
    'edges', struct('vertices', {}, 'curve', {}), ...
    'surfaces', {{}}, ...
    'faces', struct('surface', {}, 'same_sense', {}, 'loops', {}), ...
    'bodies', struct('name', {}, 'kind', {}, 'shells', {}));
end
